"""Build static language homepages. Run after editing templates/home.html or locales/*.json."""
import argparse
import json
import re
from html import escape
from pathlib import Path
from project_locales import PROJECTS, UI, SANKEY, project_outputs

ROOT = Path(__file__).resolve().parents[1]
from site_locales import LANGUAGES

ORIGIN = 'https://zandaulion.com/'


def build(check=False):
    template = (ROOT / 'templates/home.html').read_text(encoding='utf-8')
    english = json.loads((ROOT / 'locales/en-US.json').read_text(encoding='utf-8'))
    outputs, registry = {}, []
    alternates = '\n  '.join(
        f'<link rel="alternate" hreflang="{lang}" href="{ORIGIN}{path + "/" if path else ""}">'
        for lang, path, _, _ in LANGUAGES
    ) + f'\n  <link rel="alternate" hreflang="x-default" href="{ORIGIN}">'
    for lang, path, name, direction in LANGUAGES:
        catalog = json.loads((ROOT / f'locales/{lang}.json').read_text(encoding='utf-8'))
        if catalog.keys() != english.keys():
            raise ValueError(f'{lang}: missing {english.keys() - catalog.keys()}; extra {catalog.keys() - english.keys()}')
        if any(not isinstance(value, str) or not value.strip() for value in catalog.values()):
            raise ValueError(f'{lang}: every translation must be non-empty text')
        root = '../' if path else ''
        links = []
        for target, target_path, native, target_dir in LANGUAGES:
            url = root + (target_path + '/' if target_path else '') + 'index.html'
            if not target_path:
                url += '?lang=en-US'
            current = ' aria-current="page"' if target == lang else ''
            links.append(f'<a href="{url}" lang="{target}" hreflang="{target}" dir="{target_dir}" data-language="{target}"{current}>{native}</a>')
        picker = (f'<details class="language-picker"><summary><span aria-hidden="true">◎</span> '
                  f'<span lang="{lang}" dir="{direction}">{name}</span><span class="sr-only"> — {escape(catalog["language"])}</span></summary>'
                  f'<nav class="language-list" aria-label="{escape(catalog["language"])}">' + ''.join(links) + '</nav></details>')
        note = '' if not path else f'<p class="translation-note wrap">{escape(catalog["translation_note"])}</p>'
        context = {key: escape(value, quote=True) for key, value in catalog.items()}
        context.update(root=root, lang=lang, direction=direction, canonical=ORIGIN + (path + '/' if path else ''),
                       locale_home='index.html', alternates=alternates, language_picker=picker, translation_note=note)
        def replace(match):
            key = match[1]
            if key not in context:
                raise ValueError(f'Unknown template key: {key}')
            return context[key]
        content = re.sub(r'\{\{([a-z_]+)\}\}', replace, template)
        for filename in PROJECTS.get(lang, ()):
            content = content.replace(f'href="{root}{filename}" hreflang="en-US"', f'href="{filename}" hreflang="{lang}"')
        content = '\n'.join(line.rstrip() for line in content.splitlines()) + '\n'
        outputs[ROOT / path / 'index.html'] = content
        shared = {key: catalog[key] for key in ('language', 'collection', 'about', 'hello', 'nav', 'home', 'return_home', 'english_page', 'skip', 'coffee', 'privacy', 'formerly')}
        messages = {} if lang == 'en-US' else json.loads((ROOT / f'locales/projects/{lang}/common.json').read_text(encoding='utf-8'))
        ui = {key: messages[value] if path else value for key, value in UI.items()}
        if '{n}' not in ui['count'] or '{total}' not in ui['count']:
            raise ValueError(f'{lang}: gallery count placeholders must be preserved')
        sankey = {value: messages[value] if path else value for value in SANKEY}
        registry.append(dict(lang=lang, path=path, name=name, dir=direction, projects=PROJECTS.get(lang, ()), ui=ui, sankey=sankey, **shared))
    outputs.update(project_outputs(ROOT))
    outputs[ROOT / 'language-data.js'] = '// Generated by scripts/build_locales.py.\nwindow.ZandaulionLocales = ' + json.dumps(registry, ensure_ascii=False, indent=2) + ';\n'
    stale = []
    for output, content in outputs.items():
        if check:
            if not output.exists() or output.read_text(encoding='utf-8') != content:
                stale.append(str(output.relative_to(ROOT)))
        else:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(content, encoding='utf-8', newline='\n')
    if stale:
        raise SystemExit('Rebuild stale outputs: ' + ', '.join(stale))
    print(f'PASS: {len(LANGUAGES)} complete catalogs; static pages {"verified" if check else "built"}.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if generated files need rebuilding')
    build(parser.parse_args().check)
